# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'newsapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for newsapp
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 4.9.1'
  pod 'Toast-Swift', '~> 5.0.0'
  pod "SwiftSpinner"
  pod 'Charts'
  pod 'XLPagerTabStrip', '~> 9.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'Toast-Swift', '~> 5.0.1'

end
